
import { ContentItem, Elements } from '@kentico/kontent-delivery';
import { BenefitTile } from './benefit_tile';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 17 2019 18:39:11 GMT+1100 (Australian Eastern Daylight Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class BenefitsList extends ContentItem {
    public benefitTiles: Elements.LinkedItemsElement<BenefitTile>;
    public heading: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'benefit_tiles') {
                    return 'benefitTiles';
                }
                return elementName;
            })
        });
    }
}
