
import { ContentItem, Elements } from '@kentico/kontent-delivery';
import { BenefitsList } from './benefits_list';
import { TestimonialTile } from './testimonial_tile';
import { TechnologyTile } from './technology_tile';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 17 2019 18:39:11 GMT+1100 (Australian Eastern Daylight Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ConsultingService extends ContentItem {
    public talkToUs: Elements.TextElement;
    public benefits: Elements.LinkedItemsElement<BenefitsList>;
    public subHeading: Elements.TextElement;
    public testimonials: Elements.LinkedItemsElement<TestimonialTile>;
    public body: Elements.RichTextElement;
    public technologyTiles: Elements.LinkedItemsElement<TechnologyTile>;
    public heading: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'talk_to_us___') {
                    return 'talkToUs';
                }
                if (elementName === 'sub_heading') {
                    return 'subHeading';
                }
                if (elementName === 'technology_tiles') {
                    return 'technologyTiles';
                }
                return elementName;
            })
        });
    }
}
