
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 17 2019 18:39:11 GMT+1100 (Australian Eastern Daylight Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class EmbedYoutube extends ContentItem {
    public videoTitle: Elements.TextElement;
    public videoId: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'video_title') {
                    return 'videoTitle';
                }
                if (elementName === 'video_id') {
                    return 'videoId';
                }
                return elementName;
            })
        });
    }
}
