
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 17 2019 18:39:11 GMT+1100 (Australian Eastern Daylight Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TechnologyTile extends ContentItem {
    public body: Elements.RichTextElement;
    public image: Elements.AssetsElement;
    public heading: Elements.TextElement;
}
